version: 2

models:
    - name: stg_events
      columns:
        - name: invoice_no
          tests:
            - not_null
        - name: stock_code
          tests:
            - not_null
        - name: invoice_date
          tests:
            - not_null
        - name: load_date
          tests:
            - not_null